### ISSUE TITLE
[Server]MVC 구조에 따른 파일 구성

### ISSUE THREAD

**Issue by pgj0116** [codestates/underTheSea#3]
### **ISSUE**

- Group: `server`
- Type:  `feature`
- Detail: MVC 구조에 따른 파일 구성

### **TODO**

- [ ]  Model 폴더 및 관련 기본 파일 만들기
- [ ]  Controller 폴더 및 관련 기본 파일 만들기
- [ ]  Router 폴더 및 관련 파일 만들기
