### ISSUE TITLE
[Server]Sequelize 사용한 테이블 작성

### ISSUE THREAD

**Issue by pgj0116** [codestates/underTheSea#4]
### **ISSUE**

- Group: `server`
- Type: `feature`
- Detail: Sequelize 사용한 테이블 작성

### **TODO**

- [ ]  Sequelize 모듈 설치
- [ ]  migration schema 작성
- [ ]  seeder를 사용해서 dummy data 삽입
