### ISSUE TITLE
[Server]API 바탕으로 controller 파일 작성

### ISSUE THREAD

**Issue by pgj0116** [codestates/underTheSea#8]
### **ISSUE**

- Group:  `server`
- Type: `feature`
- Detail: 엔드포인트에 따른 분기, 메소드에 따른 올바른 쿼리문 작성

### **TODO**

- [ ]  DELETE /admin/account
- [ ]  DELETE /admin/comtainer
- [ ]  POST /admin/fish
- [ ]  PATCH /admin/fish/:fish_name
- [ ]  DELETE /admin/fish/:fish_name
- [ ]  DELETE /admin/tip/:tip_id
- [ ]  POST /user/signup
- [ ]  POST /user/login
- [ ]  POST /user/logout
- [ ]  DELETE /user
- [ ]  GET /user
- [ ]  PATCH /user/password
- [ ]  POST /container/add
- [ ] GET /container/:container_id/:month
- [ ] PATCH /container/:container_id
- [ ] DELETE /container/:container_id
- [ ] GET /container/:container_id/level
- [ ] POST /container/:container_id/fish
- [ ] POST /container/:container_id/feed
- [ ] POST /container/:container_id/ex_water
- [ ] GET /fish/:fish_name/
- [ ] GET /tip
- [ ] POST /tip
- [ ] PATCH /tip/:tip_id
- [ ] DELETE /tip/:tip_id
- [ ] POST /tip/:tip_id/comment
- [ ] DELETE /tip/:comment_id
