### ISSUE TITLE
[Client] 통신 프로토콜 작성 - 데이터 핸들링

### ISSUE THREAD

**Issue by JeongSeongWu** [codestates/underTheSea#9]
### ISSUE
 - Group: `client`
 - Type: `feature`
 - Detail: 
### TODO
- [ ] 어종별 정보 검색기능 추가
- [ ] 물생활 정보 공유 게시판 추가
- [ ] 나의 수조 등록기능 추가
- [ ] 수조 관리기능 추가
